language: node_js

node_js:
  - "8.10.0"

cache:
  directories:
    - "node_modules"
    
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - npm test

after_success:
- npm run coveralls